services:
  backend:
    build: .
    env_file:
      - ../frontend/.env
    environment:
      - PORT_DOCKER_INTERNAL_BACKEND=${PORT_DOCKER_INTERNAL_BACKEND}
    ports:
      - "${PORT_BACKEND_EXTERNAL}:${PORT_DOCKER_INTERNAL_BACKEND}"
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT_DOCKER_INTERNAL_BACKEND}/api/hello"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 20s
    networks:
      - neiwa-net

networks:
  neiwa-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.13.0.0/16
